baseurl = "https://henyxia.github.io/"
title = "henyxia's website"
theme = "i-am-not-a-css-designer"
canonifyurls = true
hasCJKLanguage = true
googleAnalytics = "UA-146517157-1"

[params]
    author = "Jean Wasilewski"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        I love doing computer stuff.
        Open source and free software for the win!
    """
    publicationYear = "2019"

[outputs]
    section = ["HTML"]

[[menu.shortlink]]
    identifier = "blog"
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/projects/"
    weight = 10

[[menu.shortlink]]
    identifier = "scholar"
    pre = "<i class='fas fa-graduation-cap fa-lg'></i>"
    url = "/scholar/"
    weight = 15

[[menu.shortlink]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/henyxia"
    weight = 20

[[menu.shortlink]]
    identifier = "linkedin"
    pre = "<i class='fab fa-linkedin fa-lg'></i>"
    url = "https://www.linkedin.com/in/jeanwasilewski/"
    weight = 30

[[menu.shortlink]]
    identifier = "email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:hire-me@revs0.com"
    weight = 40

[[menu.shortlink]]
    identifier = "note"
    pre = "<i class='fa fa-sticky-note fa-lg'></i>"
    url = "/notes/"
    weight = 50
